name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v1
    - name: Run unit test
      run: |
        set -o pipefail && xcodebuild test -workspace ShadowsocksX-NG.xcworkspace -scheme ShadowsocksX-NG|xcpretty
    - name: build
      run: |
        set -o pipefail && xcodebuild -workspace ShadowsocksX-NG.xcworkspace -config Release -scheme ShadowsocksX-NG|xcpretty
    - name: export
      run: |
        xcodebuild -exportArchive -exportPath 'ShadowsocksX-NG.app' -exportFormat App
